---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "6"
spec:
  template:
    spec:
      containers:
      - image: busybox
        name: gitops
        command:
        - echo
        - revision={{ .Values.revision }}
      restartPolicy: Never
  backoffLimit: 3
