---
apiVersion: batch/v1
kind: Job
metadata:
  name: iam-automated-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      initContainers:
      - image: busybox:1.32
        name: wait-for-iam
        command:
        - sh
        - -c
        - timeout 60 sh -c 'until nc -z $0 $1; do sleep 1; done' iam 9000
      containers:
      - image: "{{ .Values.iamautomatedtest.image }}:{{ .Values.iamautomatedtest.tag }}"
        name: iam-automated-test
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_ADDRESS
          value: iam:9000
      restartPolicy: Never
  backoffLimit: 3
