---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
      - image: "{{ .Values.resourcemanager.image }}:{{ .Values.resourcemanager.tag }}"
        name: resourcemanager
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_SERVER_PORT
          value: "9000"
        - name: MYSQL_USER
          value: {{ .Values.mysql.mysqlUser }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.mysqlPassword }}
        - name: MYSQL_HOST
          value: "{{ .Release.Name }}-mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: cloud
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
spec:
  ports:
  - name: http2
    port: 9000
    protocol: TCP
  selector:
    app: resourcemanager
  type: ClusterIP
