---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/nokamoto/demo20-apps-config
    targetRevision: development
    helm:
      valueFiles:
        - values.yaml
        - values-development.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
