authorizer:
  image: ghcr.io/nokamoto/demo20-apps/demo20-authorizer
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
compute:
  image: ghcr.io/nokamoto/demo20-apps/demo20-compute
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
computeautomatedtest:
  image: ghcr.io/nokamoto/demo20-apps/demo20-compute-automated-test
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
iam:
  image: ghcr.io/nokamoto/demo20-apps/demo20-iam
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
iamautomatedtest:
  image: ghcr.io/nokamoto/demo20-apps/demo20-iam-automated-test
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
mysql:
  initializationFiles:
    init.sql: |-
      CREATE DATABASE cloud;

      GRANT ALL ON cloud.* TO 'test'@'%';

      USE cloud;

      CREATE TABLE resourcemanager_project (
          project_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          project_id VARCHAR(256) UNIQUE,
          display_name VARCHAR(256)
      );

      CREATE TABLE compute_instance (
          instance_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          instance_id VARCHAR(256) UNIQUE,
          parent_id VARCHAR(256),
          labels VARCHAR(256),
          FOREIGN KEY (parent_id) REFERENCES resourcemanager_project (project_id)
      );

      CREATE TABLE iam_permission (
          permission_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          permission_id VARCHAR(256) UNIQUE
      );

      CREATE TABLE iam_role (
          role_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          role_id VARCHAR(256) UNIQUE,
          parent_id VARCHAR(256),
          display_name VARCHAR(256),
          FOREIGN KEY (parent_id) REFERENCES resourcemanager_project (project_id)
      );

      CREATE TABLE iam_role_permission (
          role_key BIGINT,
          permission_key BIGINT,
          FOREIGN KEY (role_key) REFERENCES iam_role (role_key),
          FOREIGN KEY (permission_key) REFERENCES iam_permission (permission_key)
      );

      CREATE TABLE iam_role_binding (
          role_key BIGINT,
          user VARCHAR(256),
          parent_id VARCHAR(256),
          FOREIGN KEY (role_key) REFERENCES iam_role (role_key),
          FOREIGN KEY (parent_id) REFERENCES resourcemanager_project (project_id)
      );

      CREATE TABLE iam_machine_user (
          machine_user_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          machine_user_id VARCHAR(256) UNIQUE,
          display_name VARCHAR(256),
          parent_id VARCHAR(256),
          FOREIGN KEY (parent_id) REFERENCES resourcemanager_project (project_id)
      );

      CREATE TABLE rdb_cluster (
          cluster_key BIGINT PRIMARY KEY AUTO_INCREMENT,
          cluster_id VARCHAR(256) UNIQUE,
          parent_id VARCHAR(256),
          replicas INT,
          FOREIGN KEY (parent_id) REFERENCES resourcemanager_project (project_id)
      );

      CREATE TABLE rdb_cluster_instance (
          cluster_key BIGINT,
          instance_id VARCHAR(256),
          FOREIGN KEY (cluster_key) REFERENCES rdb_cluster (cluster_key),
          FOREIGN KEY (instance_id) REFERENCES compute_instance (instance_id)
      );

      INSERT INTO resourcemanager_project (
          project_id,
          display_name
      ) VALUES
          ('/', 'root'),
          ('todo', 'todo display name');
  mysqlPassword: test
  mysqlUser: test
namespace: local
rdb:
  image: ghcr.io/nokamoto/demo20-apps/demo20-rdb
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
rdbautomatedtest:
  image: ghcr.io/nokamoto/demo20-apps/demo20-rdb-automated-test
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
resourcemanager:
  image: ghcr.io/nokamoto/demo20-apps/demo20-resourcemanager
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
resourcemanagerautomatedtest:
  image: ghcr.io/nokamoto/demo20-apps/demo20-resourcemanager-automated-test
  tag: 4a7f41d0fee0c98d116a74a3bc73aa12935ceea5
