name: Helm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Helm directory
      uses: actions/checkout@v2
    - name: Make
      run: make
  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - run: |
        docker run \
          -e GIT_BRANCH=development\
          -e GIT_SHA=$GITHUB_SHA\
          -e GH_PAT=${{ secrets.GH_PAT }}\
          ghcr.io/nokamoto/demo20-gitops-plugin:97d0d3f8e154e01a2eaca69bc0a81f3798223b62
