name: Helm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Helm directory
      uses: actions/checkout@v2
    - name: Make
      run: make
  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push'
    steps:
    - name: Check out code into the Helm directory
      uses: actions/checkout@v2
    - run: |
        git config --local user.email "nokamoto.engr@gmail.com"
        git config --local user.name "nokamoto"
        git remote add development https://${{ secrets.GH_PAT }}@github.com/nokamoto/demo20-apps-config.git
        git fetch development
        git checkout development
        git merge master
        git push development development
